Delay dropping of root privileges
geekman/mdns-repeater pull request #22
Opened 2023-07-29 22:19 UTC by axkg

The early dropping of root privileges as introduced with #18 does not work for me, as binding an interface requires root. Without it mdns-repeater reports an error:

`mdns-repeater: send setsockopt(SO_BINDTODEVICE): Operation not permitted`

This PR delays the dropping of the root privileges and moves daemonize() post the opening of the sockets to ensure the pid file is created for the same user that is expected to unlink() it on shutdown.

2023-08-01 14:50 UTC, geekman requested changes

2023-08-01 14:50 UTC, geekman commented on mdns-repeater.c
> +const struct passwd* user;
perhaps use `user == NULL` instead of having an additional variable as a flag

2023-08-01 14:50 UTC, geekman commented on mdns-repeater.c
> +
remove excess empty line

2023-08-01 16:06 UTC, axkg commented
Dropped the flag (and the excess line) as requested, works for me for both cases (with and without -u switch).

2023-08-02 17:58 UTC, geekman commented
Alright, looks good. Thanks!

2023-08-02 17:59 UTC, merged